'use client'
import { useEffect, useMemo, useState } from 'react'
import { ensureAccount } from '@/lib/data'
import { supabaseBrowser } from '@/lib/supabase-browser'

type WeightEntry={measured_on:string;weight_kg:number}
type SportSession={id:string;session_date:string;sport:string;distance_km:number|null;duration_seconds:number|null;pace_seconds_per_km:number|null;avg_heart_rate:number|null;max_heart_rate:number|null;notes:string|null}

function bmiLabel(b:number){if(b<18.5)return'Insuffisance pondérale';if(b<25)return'Corpulence normale';if(b<30)return'Surpoids';if(b<35)return'Obésité classe I';if(b<40)return'Obésité classe II';return'Obésité classe III'}
function fmtPace(sec:number|null){if(!sec)return'—';return`${Math.floor(sec/60)}:${String(Math.round(sec%60)).padStart(2,'0')}/km`}
function fmtDuration(sec:number|null){if(!sec)return'—';const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;return h?`${h}h ${String(m).padStart(2,'0')}`:`${m} min${s?` ${String(s).padStart(2,'0')} s`:''}`}
function paceFrom(distance:number,duration:string){const parts=duration.split(':').map(Number);let sec=0;if(parts.length===2)sec=parts[0]*60+parts[1];else if(parts.length===3)sec=parts[0]*3600+parts[1]*60+parts[2];return distance>0&&sec>0?Math.round(sec/distance):null}

export default function Tracking(){
 const [uid,setUid]=useState('');const [height,setHeight]=useState('');const [goal,setGoal]=useState('');const [weight,setWeight]=useState('');
 const [entries,setEntries]=useState<WeightEntry[]>([]);const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [name,setName]=useState('Clément');
 const [sessions,setSessions]=useState<SportSession[]>([]);const [sport,setSport]=useState('Course');const [sportDate,setSportDate]=useState(new Date().toISOString().slice(0,10));const [distance,setDistance]=useState('');const [duration,setDuration]=useState('');const [avgHr,setAvgHr]=useState('');const [maxHr,setMaxHr]=useState('');const [notes,setNotes]=useState('');
 async function load(){const a=await ensureAccount();if(!a)return;setUid(a.user.id);setName(a.profile?.first_name||'Clément');setHeight(a.profile?.height_cm?.toString()||'');setGoal(a.profile?.target_weight_kg?.toString()||'');
  const sb=supabaseBrowser();const w=await sb.from('weight_entries').select('measured_on,weight_kg').eq('user_id',a.user.id).order('measured_on');setEntries((w.data||[]) as WeightEntry[]);
  const s=await sb.from('sport_sessions').select('id,session_date,sport,distance_km,duration_seconds,pace_seconds_per_km,avg_heart_rate,max_heart_rate,notes').eq('user_id',a.user.id).order('session_date',{ascending:false});setSessions((s.data||[]) as SportSession[])
 }
 useEffect(()=>{load()},[])
 async function saveWeight(){if(!uid||!weight)return;const sb=supabaseBrowser();await sb.from('weight_entries').upsert({user_id:uid,measured_on:date,weight_kg:Number(weight)},{onConflict:'user_id,measured_on'});await sb.from('profiles').update({height_cm:height?Number(height):null,target_weight_kg:goal?Number(goal):null,updated_at:new Date().toISOString()}).eq('id',uid);setWeight('');load()}
 async function saveSport(){if(!uid||!distance||!duration)return;const d=Number(distance), pace=paceFrom(d,duration);const parts=duration.split(':').map(Number);let sec=0;if(parts.length===2)sec=parts[0]*60+parts[1];else if(parts.length===3)sec=parts[0]*3600+parts[1]*60+parts[2];if(!pace||!sec)return;await supabaseBrowser().from('sport_sessions').insert({user_id:uid,session_date:sportDate,sport,distance_km:d,duration_seconds:sec,pace_seconds_per_km:pace,avg_heart_rate:avgHr?Number(avgHr):null,max_heart_rate:maxHr?Number(maxHr):null,notes:notes||null,source:'manual'});setDistance('');setDuration('');setAvgHr('');setMaxHr('');setNotes('');load()}
 async function deleteSport(id:string){await supabaseBrowser().from('sport_sessions').delete().eq('id',id);load()}
 const current=entries.at(-1)?.weight_kg??null;const bmi=useMemo(()=>current&&height?current/((Number(height)/100)**2):null,[current,height]);const start=entries[0]?.weight_kg??null;const delta=current&&start?current-start:null;
 const chart=useMemo(()=>{if(entries.length<2)return null;const W=640,H=210,pad=30,min=Math.min(...entries.map(e=>e.weight_kg)),max=Math.max(...entries.map(e=>e.weight_kg)),range=Math.max(max-min,1);const points=entries.map((e,i)=>`${pad+(i/(entries.length-1))*(W-pad*2)},${H-pad-((e.weight_kg-min)/range)*(H-pad*2)}`).join(' ');return {W,H,pad,min,max,points}},[entries]);
 const sportTotals=useMemo(()=>{const runs=sessions.filter(s=>s.sport==='Course');const distance=runs.reduce((a,s)=>a+(s.distance_km||0),0);const duration=runs.reduce((a,s)=>a+(s.duration_seconds||0),0);const marathonKm=42.195;return {count:runs.length,distance,duration,marathonPct:Math.min(distance/marathonKm*100,100)}},[sessions]);
 return <><div className="top"><div><div className="muted">Profil : {name}</div><h1>Suivi</h1></div></div>
 <section className="card"><div className="row"><div><div className="muted">Poids actuel</div><div className="total">{current?`${current.toFixed(1).replace('.',',')} kg`:'—'}</div></div><div><div className="muted">Objectif</div><strong>{goal?`${goal} kg`:'À définir'}</strong></div></div>{delta!==null&&<p className="muted">Évolution depuis la première pesée : {delta>0?'+':''}{delta.toFixed(1)} kg</p>}</section>
 {chart&&<section className="card"><h2>Évolution du poids</h2><div className="chartwrap"><svg viewBox={`0 0 ${chart.W} ${chart.H}`} role="img" aria-label="Évolution du poids"><polyline points={chart.points} fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/>{entries.map((e,i)=>{const [x,y]=chart.points.split(' ')[i].split(',');return <circle key={e.measured_on} cx={x} cy={y} r="4" fill="currentColor"/>})}</svg><div className="row small"><span>{entries[0].weight_kg.toFixed(1)} kg</span><span>{entries.at(-1)!.weight_kg.toFixed(1)} kg</span></div></div></section>}
 <section className="card"><h2>Mes paramètres</h2><div className="form"><label>Taille (cm)<input type="number" step="0.1" value={height} onChange={e=>setHeight(e.target.value)}/></label><label>Objectif (kg)<input type="number" step="0.1" value={goal} onChange={e=>setGoal(e.target.value)}/></label><button className="btn" onClick={saveWeight}>Enregistrer</button></div></section>
 <section className="card"><h2>Ajouter une pesée</h2><div className="form"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><input type="number" placeholder="Poids (kg)" step="0.1" value={weight} onChange={e=>setWeight(e.target.value)}/><button className="btn" onClick={saveWeight}>Enregistrer</button></div></section>
 <section className="card"><h2>IMC</h2>{bmi?<><div className="total">{bmi.toFixed(1).replace('.',',')}</div><div className="tag">{bmiLabel(bmi)}</div><p className="muted small">L’IMC est un indicateur de dépistage, pas un diagnostic.</p></>:<p className="muted">Ajoute ta taille et une pesée pour calculer automatiquement l’IMC.</p>}</section>
 <section className="card"><div className="row"><div><h2>Sport</h2><p className="muted">Course, distance, allure et fréquence cardiaque.</p></div><div className="tag">{sportTotals.count} sorties · {sportTotals.distance.toFixed(1)} km</div></div><div className="form"><select value={sport} onChange={e=>setSport(e.target.value)}><option>Course</option><option>Marche</option><option>Vélo</option><option>Natation</option><option>Autre</option></select><input type="date" value={sportDate} onChange={e=>setSportDate(e.target.value)}/><input type="number" placeholder="Distance (km)" step="0.01" value={distance} onChange={e=>setDistance(e.target.value)}/><input placeholder="Durée (mm:ss ou hh:mm:ss)" value={duration} onChange={e=>setDuration(e.target.value)}/><div className="row"><input type="number" placeholder="FC moy." value={avgHr} onChange={e=>setAvgHr(e.target.value)}/><input type="number" placeholder="FC max" value={maxHr} onChange={e=>setMaxHr(e.target.value)}/></div><input placeholder="Note (facultatif)" value={notes} onChange={e=>setNotes(e.target.value)}/><button className="btn" onClick={saveSport}>Ajouter la séance</button></div><div className="progress"><div className="progressbar"><span style={{width:`${sportTotals.marathonPct}%`}} /></div><div className="row small"><span>Volume course cumulé</span><strong>{sportTotals.distance.toFixed(1)} / 42,2 km</strong></div></div></section>
 <section className="card"><h2>Dernières séances</h2>{sessions.length?sessions.slice(0,10).map(s=><div className="history" key={s.id}><div className="row"><span><strong>{s.sport}</strong> · {new Date(s.session_date+'T12:00:00').toLocaleDateString('fr-FR')}</span><button className="textbtn" onClick={()=>deleteSport(s.id)}>Supprimer</button></div><div className="muted small">{s.distance_km?s.distance_km.toFixed(2)+' km':''}{s.duration_seconds?` · ${fmtDuration(s.duration_seconds)}`:''}{s.pace_seconds_per_km?` · ${fmtPace(s.pace_seconds_per_km)}`:''}{s.avg_heart_rate?` · FC ${s.avg_heart_rate}`:''}</div></div>):<p className="muted">Aucune séance enregistrée.</p>}</section>
 <section className="card"><h2>Historique du poids</h2>{entries.length?entries.slice().reverse().map(e=><div className="row history" key={e.measured_on}><span>{new Date(e.measured_on+'T12:00:00').toLocaleDateString('fr-FR')}</span><strong>{e.weight_kg.toFixed(1)} kg</strong></div>):<p className="muted">Aucune pesée enregistrée.</p>}</section></>}
