'use client'
import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { supabaseBrowser } from '@/lib/supabase-browser'

type Recipe={id:string;title:string;category:string;kcal_per_serving:number|null;vegetarian:boolean;description:string|null;prep_minutes:number;cook_minutes:number;default_servings:number;instructions:string[]}
type RI={quantity:number;unit:string;note:string|null;ingredients:{name:string}|null}
const labels:Record<string,string>={petit_dejeuner:'Petits-déjeuners',leger:'Légers',vegetarien:'Végétariens',reconfort:'Réconfort',dessert:'Desserts',encas:'Encas & goûters'}
const art:Record<string,string>={petit_dejeuner:'☀️',leger:'🥗',vegetarien:'🌱',reconfort:'🍲',dessert:'🍓',encas:'🍎'}
export default function Recipes(){const params=useSearchParams();const [recipes,setRecipes]=useState<Recipe[]>([]);const [cat,setCat]=useState('all');const [query,setQuery]=useState('');const [selected,setSelected]=useState<Recipe|null>(null);const [ingredients,setIngredients]=useState<RI[]>([]);const [servings,setServings]=useState(1)
 useEffect(()=>{supabaseBrowser().from('recipes').select('id,title,category,kcal_per_serving,vegetarian,description,prep_minutes,cook_minutes,default_servings,instructions').order('title').then(({data})=>{const rs=data||[];setRecipes(rs);const id=params.get('recipe');if(id){const r=rs.find(x=>x.id===id);if(r)openRecipe(r)}})},[])
 async function openRecipe(r:Recipe){setSelected(r);setServings(r.default_servings||1);const {data}=await supabaseBrowser().from('recipe_ingredients').select('quantity,unit,note,ingredients(name)').eq('recipe_id',r.id).order('sort_order');setIngredients((data||[]) as any)}
 const shown=useMemo(()=>recipes.filter(r=>(cat==='all'||r.category===cat)&&r.title.toLowerCase().includes(query.toLowerCase())),[recipes,cat,query])
 const scale=(q:number)=>q*(servings/(selected?.default_servings||1))
 return <><div className="top"><div><div className="muted">Bibliothèque</div><h1>Recettes</h1></div><span className="tag">{recipes.length}</span></div><input className="search" placeholder="Rechercher une recette…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="chips"><button className={cat==='all'?'chip active':'chip'} onClick={()=>setCat('all')}>Toutes</button>{Object.entries(labels).map(([k,v])=><button className={cat===k?'chip active':'chip'} key={k} onClick={()=>setCat(k)}>{v}</button>)}</div><div className="recipegrid">{shown.map(r=><button className="recipe" key={r.id} onClick={()=>openRecipe(r)}><div className="art">{art[r.category]||'🍽️'}</div><div className="body"><span className="tag">{labels[r.category]||r.category}</span><h3>{r.title}</h3><div className="kcal">{r.kcal_per_serving?`${Math.round(r.kcal_per_serving)} kcal / portion`:'Calories à valider'} · {r.prep_minutes+r.cook_minutes} min</div></div></button>)}</div>
 {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="bigart">{art[selected.category]||'🍽️'}</div><span className="tag">{labels[selected.category]}</span><h2>{selected.title}</h2><p className="muted">{selected.description}</p><p><strong>{selected.prep_minutes+selected.cook_minutes} min</strong> · {selected.kcal_per_serving?`${Math.round(selected.kcal_per_serving*(servings/(selected.default_servings||1)))} kcal`:''}</p><label className="servings">Portions <input type="number" min="1" max="20" value={servings} onChange={e=>setServings(Math.max(1,Number(e.target.value)||1))}/></label><h3>Ingrédients</h3>{ingredients.length?<ul>{ingredients.map((x,i)=><li key={i}>{Math.round(scale(Number(x.quantity))*10)/10} {x.unit} · {x.ingredients?.name}{x.note?` (${x.note})`:''}</li>)}</ul>:<p className="muted">Aucun ingrédient renseigné.</p>}<h3>Préparation</h3><ol>{(selected.instructions||[]).map((s,i)=><li key={i}>{s}</li>)}</ol></div></div>}</>}
